#!/usr/bin/env python3

import os
import subprocess

for dn in ('build', 'bin'):
    if not os.path.exists(dn):
        os.makedirs(dn)

env = SConscript("../godot-cpp/SConstruct")

platform, target, arch, suffix, ext = [
    env[name] for name in ('platform', 'target', 'arch', 'suffix', 'SHLIBSUFFIX')
]

build_dn = f"build/{platform}-{target}-{arch}"
if not os.path.exists(build_dn):
    os.makedirs(build_dn)

env.VariantDir(build_dn, '3-football-on-paper/sources', duplicate=0)

ais = [
    'mcts/ai.c',
    'mcts/dev-0003.c',
    'random-ai.c',
]

hashes_h_target = "3-football-on-paper/include/hashes.h"
hashes_h_sources = [
    '3-football-on-paper/sources/calc-hash.awk',
    *[ f"3-football-on-paper/sources/{ai}" for ai in ais ]
]

def generate_hashes_h(target, source, env):
    sources_dn = '3-football-on-paper/sources'
    hashes_h = os.path.abspath(str(target[0]))

    sha_cmd_args = " ".join(ais)
    cmd = f"sha512sum {sha_cmd_args} | awk -f calc-hash.awk > {hashes_h}"

    p = subprocess.run(cmd, shell=True, check=True, cwd=sources_dn)
    return p.returncode

hashes_h_command = env.Command(hashes_h_target, hashes_h_sources, generate_hashes_h)

sources = [
    "src/wrapper.cpp",
    "src/bridge.c",
    f"{build_dn}/utils.c",
    f"{build_dn}/warns.c",
    f"{build_dn}/game.c",
    f"{build_dn}/enginelib.c",
    f"{build_dn}/mcts/ai.c",
    f"{build_dn}/mcts/dev-0003.c",
    f"{build_dn}/random-ai.c",
    ]

env.Append(CPPPATH=["3-football-on-paper/include/"])

library = env.SharedLibrary( f"bin/libengine{suffix}{ext}", source=sources)

env.Depends(library, hashes_h_command)

Default(library)
